### ISSUE TITLE
License question

### ISSUE THREAD

**Issue by tim77** [rafi/awesome-vim-colorschemes#12]
License is unclear, could you add license file please? Also some themes under MIT license but some of them without with unclear license.

**Comment by rafi** [comment]
There's a little script [`pull_updates.sh`](https://github.com/rafi/awesome-vim-colorschemes/blob/master/pull-updates.sh) that copies all colorschemes' `README.md`.

You can often find the individual license in the actual `vim` file, or find the appropriate README in `./docs/`. You can also find a table listing all colorschemes with their respective upstream address, let me know if this helps.

**Comment by tim77** [comment]
> let me know if this helps.

LGTM. Thank you! Now [this PR](https://github.com/rafi/awesome-vim-colorschemes/pull/13) and ready for including in official Fedora repos.
