### ISSUE TITLE
Consider Oceanic Material

### ISSUE THREAD

**Issue by adrian5** [rafi/awesome-vim-colorschemes#17]
[Oceanic Material](https://github.com/hardcoreplayers/oceanic-material) seems worth a look. I gave it a try with a few languages and didn't find any issues. Totally up to you though, I understand not every theme can be included.

p.s. Unless I'm mistaken, **sainnhe/sonokai** should be just **sonokai** in the table in your README.md.

**Comment by rafi** [comment]
Thanks @adrian5, indeed a lovely colorscheme, added.
