### ISSUE TITLE
scripts errors 

### ISSUE THREAD

**Issue by goblinrieur** [rafi/awesome-vim-colorschemes#20]
hello, putting colorsthemes is ok.

but script make an error : 

`👨francois@💻zaphod🐙:~/tmp/awesome-vim-colorschemes$ bash pull-updates.sh
pull-updates.sh: line 11: HOMEBREW_GITHUB_API_TOKEN: unbound variable

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
👨francois@💻zaphod🐙:~/tmp/awesome-vim-colorschemes$ ./pull-updates.sh
./pull-updates.sh: line 11: HOMEBREW_GITHUB_API_TOKEN: unbound variable

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
👨francois@💻zaphod🐙:~/tmp/awesome-vim-colorschemes$ `

seems to be missing variable assignement in pull-updates.sh

regards.

**Comment by rafi** [comment]
Hi @goblinrieur. Because the script pulls many repositories, you don't want to hit GitHub's rate-limiting. Create a token and export and environment variable named `HOMEBREW_GITHUB_API_TOKEN` so the script will use it.

**Comment by goblinrieur** [comment]
thanks.

**Comment by goblinrieur** [comment]
thanks
